export enum ProjectNames {
    E2E_TESTS_FOLDER = 'e2e',
    E2E_PLUGINS_SUBFOLDER = 'plugins',
    E2E_PLUGINS_FILE = 'plugins.js',
    E2E_SUPPORT_SUBFOLER = 'support',
    E2E_SUPPORT_FILE = 'support.js',
    E2E_TSCONFIG_FILE = 'tsconfig.common.json',
    E2E_PAGE_OBJECTS_FOLDER = 'pageObjects',
    GITIGNORE_FILE = '.gitignore',
    CONFIG_FOLDER = 'config',
    OUTPUT_FOLDER = 'dist',
    OUTPUT_CORE_FILENAME = 'main.js',
    POSTINSTALL_FOLDER = 'postinstall',
    SOURCES_FOLDER = 'src',
    CORE_ENTRY_FILE = 'index.ts',
    LIBRARY_NAME = 'e2e-behaviour-testing',
    CYPRESS_CONFIG_FILE = 'cypress.json',
}
